//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use crate::domain::collaboration::model::Entity as Collaborations;
pub use crate::domain::notification::model::Entity as Notifications;
pub use crate::domain::task::model as Tasks;
pub use crate::domain::user::model::Entity as Users;
